print("Addition:", 5 + 3)
print("Subtraction:", 5 - 3)
print("Multiplication:", 5 * 3)
print("Division:", 5 / 3)
print("Floor Division:", 5 // 3)
print("Modulus:", 5 % 3)        
print("Exponentiation:", 5 ** 3)
print("\nComparison Operators:")
print("Equal to:", 5 == 3)
print("Not equal to:", 5 != 3)
print("Greater than:", 5 > 3)   
print("Less than:", 5 < 3)
print("Greater than or equal to:", 5 >= 3)
print("Less than or equal to:", 5 <= 3) 
print("\nLogical Operators:")
print("Logical AND:", 5>3 and 3<5)
print("Logical OR:", 5>3 or 3>5)    
print("Logical NOT:", not(5>3))
